# -*- coding: utf-8 -*-
"""code1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17gbBh-VpOAu6nk0JTqh1VPwM_PX1uLWD
"""

!git clone https://github.com/MudduChaithanyaSai/internship-test2.git

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

#add respective path of the mian.csv file here
data_path = "/content/internship-test2/input/question-1/main.csv"

df = pd.read_csv(data_path)

df.shape

df.head()

df.keys()

df = df.drop(columns = "Total")

df = df.set_index("Year")

df.head()

df.index.name = None
df.head()

df.to_csv("/content/internship-test2/output/answer-1/main.csv")

