# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16zyv_trl7g_Fa15G_GlEd5C0etGGZ8O-
"""

!git clone https://github.com/MudduChaithanyaSai/internship-test2.git

import pandas as pd

data_path = "/content/internship-test2/input/question-2/main.csv"

df = pd.read_csv(data_path)

df.head()

res = df.groupby("occupation").agg({"age":["min", "max"]})

res.head()

res.to_csv("/content/internship-test2/output/answer-2/main.csv")

