# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/148A--rsK3F4HNwf2HC1GMbBdTrjYhF80
"""

#use this only if you are using google colab for running the code
!git clone https://github.com/MudduChaithanyaSai/internship-test2.git

import pandas as pd

data_path = "/content/internship-test2/input/question-3/main.csv"

df = pd.read_csv(data_path)

df.head()

df.keys()

Ind_List = list(df.keys())

# checking if Yellow Cards and Red Cards are attributes in the given df
print("Yellow Cards" in Ind_List, "Red Cards" in Ind_List)

df = df.loc[:, ["Team", "Yellow Cards", "Red Cards"]]

df.head()

df = df.sort_values(["Red Cards", "Yellow Cards"], ascending= False)

df.to_csv("/content/internship-test2/output/answer-3/main.csv")

